language: cpp
compiler:
  - gcc
  - clang


sudo: required

addons:
  apt:
    sources:
      - sourceline: 'ppa:rakhimov/boost'
  packages:
    - boost1.61

script:
  - cd IlmBase
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/packages/ilmbase
  - make install
  - ctest
  - cd ../..
  - cd OpenEXR
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/pacakges/openexr -DCMAKE_PREFIX_PATH=$HOME/packages/ilmbase/cmake
  - make install
  - travis_wait ctest
  - cd ../..
  - cd PyIlmBase
  - mkdir build
  - cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/pacakges/pyilmbase -DCMAKE_PREFIX_PATH=$HOME/packages/ilmbase/cmake
  - make install
